#!/bin/bash

## UNITTESTING
echo "python -m unittest discover -s ./lib/ -p '*__unittest.py'"

## TESTING SCRIPT ITSELF

## Test 1
python2 SPTSPD.py -n example/01_input/Test1_ALIGNM.nex -c example/01_input/Test1_META.csv -e mi.gruenstaeudl@gmail.com
echo ""
echo "Differences between current output and template:"
diff Test1_ALIGNM.embl example/02_output/Test1_ALIGNM.embl
rm Test1_ALIGNM.embl

## Test 2
python2 SPTSPD.py -n example/01_input/Amaranths_ITS_subset_ALIGN.nex -c example/01_input/Amaranths_ITS_subset_META.csv -e mi.gruenstaeudl@gmail.com
echo ""
echo "Differences between current output and template:"
diff Amaranths_ITS_subset_ALIGN.embl example/02_output/Amaranths_ITS_subset_ALIGN.embl
rm Amaranths_ITS_subset_ALIGN.embl
