#!/bin/bash

## UNITTESTING
echo 'PLEASE RUN:  python -m unittest discover -s /home/michael_science/git/michaelgruenstaeudl_SPTSPD/sptspd/tests -p "*_unittest.py"'

## TESTING SCRIPT ITSELF
SCRIPT=/home/michael_science/git/michaelgruenstaeudl_SPTSPD/scripts/nex2embl.py

## TEST 1
INF1=/home/michael_science/git/michaelgruenstaeudl_SPTSPD/sptspd/tests/data/input/Amaranths_ITS_subset_ALIGN.nex
INF2=/home/michael_science/git/michaelgruenstaeudl_SPTSPD/sptspd/tests/data/input/Amaranths_ITS_subset_META.csv
OUTF=Amaranths_ITS_subset_ALIGN.embl
TESTOUT=/home/michael_science/git/michaelgruenstaeudl_SPTSPD/sptspd/tests/data/output/Amaranths_ITS_subset_ALIGN.embl

python2 $SCRIPT -n $INF1 -c $INF2 -o $OUTF -e mi.gruenstaeudl@gmail.com
echo ""
echo "Differences between current output and template:"
diff $OUTF $TESTOUT
rm $TESTOUT
echo ""

## TEST 2
INF1=/home/michael_science/git/michaelgruenstaeudl_SPTSPD/sptspd/tests/data/input/Test1_ALIGNM.nex
INF2=/home/michael_science/git/michaelgruenstaeudl_SPTSPD/sptspd/tests/data/input/Test1_META.csv
OUTF=Test1_ALIGNM.embl
TESTOUT=/home/michael_science/git/michaelgruenstaeudl_SPTSPD/sptspd/tests/data/output/Test1_ALIGNM.embl

python2 $SCRIPT -n $INF1 -c $INF2 -o $OUTF -e mi.gruenstaeudl@gmail.com
echo ""
echo "Differences between current output and template:"
diff $OUTF $TESTOUT
rm $TESTOUT
echo ""
